[template]
src = "rabbitmq.tmpl"
dest = "/etc/rabbitmq/rabbitmq.config"
keys = [
  "/self/service",
  "/containers",
]

[definitions]
src = "definitions.tmpl"
dest = "/etc/rabbitmq/rabbitmq_definitions.json"
